#!/bin/bash
#SBATCH -N 1
#SBATCH -n 24
#SBATCH -t 24:00:00
#SBATCH -p thinnodes
cd ..
cd ..
module load gcc boost
cd Parallel/
make clean
make
cd ../ScriptsCesga/BreastCancer/
for i in `seq 1 3`;
do
	export OMP_NUM_THREADS=24
        ./../../Parallel/fast-mrmr -f $1 -a 50 >> $2
        ./../../Parallel/fast-mrmr -f $1 -a 100 >> $2
        ./../../Parallel/fast-mrmr -f $1 -a 200 >> $2

done
