#!/bin/bash
#SBATCH -N 1
#SBATCH -n 24
#SBATCH -t 24:00:00
cd ..
cd ..
module load gcc boost openmpi
cd ParallelMPI/
make clean
make
cd ../ScriptsCesga/Epsylon/
for i in `seq 1 3`;
do
	mpirun -np 1  ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 50 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray50FeaturesMain3TotalCesga
	mpirun -np 1  ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 100 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray100FeaturesMain3TotalCesga
	mpirun -np 1  ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 200 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray200FeaturesMain3TotalCesga

	mpirun -np 2 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 50 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray50FeaturesMain3TotalCesga
	mpirun -np 2 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 100 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray100FeaturesMain3TotalCesga
	mpirun -np 2 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 200 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray200FeaturesMain3TotalCesga

	mpirun -np 4 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 50 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray50FeaturesMain3TotalCesga
	mpirun -np 4 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 100 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray100FeaturesMain3TotalCesga
	mpirun -np 4 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 200 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray200FeaturesMain3TotalCesga

	mpirun -np 12 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 50 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray50FeaturesMain3TotalCesga
	mpirun -np 12 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 100 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray100FeaturesMain3TotalCesga
	mpirun -np 12 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 200 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray200FeaturesMain3TotalCesga

	mpirun -np 24 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 50 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray50FeaturesMain3TotalCesga
	mpirun -np 24 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 100 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray100FeaturesMain3TotalCesga
	mpirun -np 24 --report-bindings --map-by socket ./../../ParallelMPI/fast-mrmr -f $LUSTRE/Datasets/Mrmr/epsylon_normalized.mrmr -a 200 >> ../../../Output-Cesga/EpsylonDataset/MPI/breastMicroArray200FeaturesMain3TotalCesga
done
