#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 24:00:00
cd ..
cd ..
module load gcc boost
cd NoParallel/
make clean
make
cd ../ScriptsCesga/BreastCancer/
for i in `seq 1 3`;
do
	./../../NoParallel/fast-mrmr -f $LUSTRE/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Cesga/BreastCancer/Optimized/breastMicroArray50FeaturesMain3TotalCesga
	./../../NoParallel/fast-mrmr -f $LUSTRE/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Cesga/BreastCancer/Optimized/breastMicroArray100FeaturesMain3TotalCesga
	./../../NoParallel/fast-mrmr -f $LUSTRE/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Cesga/BreastCancer/Optimized/breastMicroArray200FeaturesMain3TotalCesga
	./../../NoParallel/fast-mrmr -f $LUSTRE/Datasets/Mrmr/breast_preprocessed.mrmr -a 1000 >> ../../../Output-Cesga/BreastCancer/Optimized/breastMicroArray1000FeaturesMain3TotalCesga
done

