#!/bin/bash
#SBATCH -N 16
#SBATCH -n 192
#SBATCH --ntasks-per-node=12
#SBATCH -c 2
#SBATCH -t 1:00:00
#SBATCH -p thinnodes
module load gcc boost openmpi
cd $1
make clean -f $8
make -f $8
cd $6 
export OMP_NUM_THREAD=2
mpirun -np 192 $7 -a 50 -f $2 >> $3
mpirun -np 192 $7 -a 100 -f $2 >> $3
mpirun -np 192 $7 -a 200 -f $2 >> $3

mpirun -np 192 $7 -a 50 -f $4 >> $5
mpirun -np 192 $7 -a 100 -f $4 >> $5
mpirun -np 192 $7 -a 200 -f $4 >> $5

