#!/bin/bash
#SBATCH -N 32
#SBATCH -n 384
#SBATCH --ntasks-per-node=12
#SBATCH -c 2
#SBATCH -t 00:30:00
#SBATCH -p thinnodes
module load gcc boost openmpi
cd $1
make clean -f $5
make -f $5
cd $6 
export OMP_NUM_THREADS=2
mpirun -np 384 $4 -a 50 -f $2 >> $3
mpirun -np 384 $4 -a 100 -f $2 >> $3
mpirun -np 384 $4 -a 200 -f $2 >> $3
