#!/bin/bash
#SBATCH -N 1
#SBATCH -n 24
#SBATCH -t 1:00:00
#SBATCH -p thinnodes
module load gcc boost openmpi
cd $1
make clean -f $5
make -f $5
cd $2
N=1
b=24
export OMP_NUM_THREADS=$b
mpirun -np 1 --report-bindings --bind-to none $6 -a 50 -f $3 >> $4
mpirun -np 1 --report-bindings --bind-to none $6 -a 100 -f $3 >> $4
mpirun -np 1 --report-bindings --bind-to none $6 -a 200 -f $3 >> $4


