#!/bin/bash
#SBATCH -N 1
#SBATCH -n 12
#SBATCH -t 40:00:00
#SBATCH -p thinnodes
module load gcc boost openmpi
cd $1
make clean
make 
cd $2
N=1
$5 -a 50 -f $3 >> $4
$5 -a 100 -f $3 >> $4
$5 -a 200 -f $3 >> $4

