#!/bin/bash
#$ -l s_rt=24:00:00,mem_free=1G
module load gcc/5.2.1 boost/gcc/openmpi-1.6.4/1.55.0
cd /home/borja.freire/TFM/Código/fast-mRMR-master/cpu-OpenMp/src/ScriptsPluton/BreastCancer/
cd ..
cd ..
cd Parallel/
make clean
make
cd ../ScriptsPluton/BreastCancer/
for i in `seq 1 3`;
do
	#$ -pe threaded 1
	export OMP_NUM_THREADS=$NSLOTS
	./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray50FeaturesTotalJorge
	./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray100FeaturesTotalJorge
	./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray200FeaturesTotalJorge
	#$ -pe threaded 2
	export OMP_NUM_THREADS=$NSLOTS
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray50FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray100FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray200FeaturesTotalJorge
	#$ -pe threaded 4
	export OMP_NUM_THREADS=$NSLOTS
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray50FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray100FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray200FeaturesTotalJorge
	#$ -pe threaded 8
	export OMP_NUM_THREADS=$NSLOTS
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray50FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray100FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray200FeaturesTotalJorge
	#$ -pe threaded 16
	export OMP_NUM_THREADS=$NSLOTS
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray50FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray100FeaturesTotalJorge
        ./../../Parallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/OpenMp/breastMicroArray200FeaturesTotalJorge
done
