#!/bin/bash
#$ -l s_rt=10:00:00,mem_free=60G,cpu_type=sandy_bridge,excl=true
module load gcc/5.3.1 boost/gcc/openmpi-1.7.2/1.55.0 openmpi/gcc/eth/1.7.2
cd /home/borja.freire/TFM/Código/fast-mRMR-master/cpu-OpenMp/src/ScriptsPluton/BreastCancer/
cd ..
cd ..
cd ParallelMPI/
make clean -f Makefile3
make -f Makefile3
cd ../ScriptsPluton/BreastCancer/
        #$ -pe mpi_1p 16
        mpirun -np 1 --bind-to-socket -x OMP_NUM_THREADS=16 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 1 --bind-to-socket -x OMP_NUM_THREADS=16 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 1 --bind-to-socket -x OMP_NUM_THREADS=16 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2

        #$ -pe mpi_2p 16
        mpirun -np 2 --bind-to-socket -x OMP_NUM_THREADS=8 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 2 --bind-to-socket -x OMP_NUM_THREADS=8 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 2 --bind-to-socket -x OMP_NUM_THREADS=8 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2

        #$ -pe mpi_4p 16
        mpirun -np 4 --bind-to-socket -x OMP_NUM_THREADS=4 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 4 --bind-to-socket -x OMP_NUM_THREADS=4 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 4 --bind-to-socket -x OMP_NUM_THREADS=4 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2

        #$ -pe mpi_8p 16
        mpirun -np 8 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 8 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 8 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2

        #$ -pe mpi_16p 16
        mpirun -np 16 --bind-to-socket -x OMP_NUM_THREADS=1 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 16 --bind-to-socket -x OMP_NUM_THREADS=1 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 16 --bind-to-socket -x OMP_NUM_THREADS=1 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2
done
