#!/bin/bash
#$ -l s_rt=24:00:00,mem_free=1G
module load gcc/5.2.1 boost/gcc/openmpi-1.6.4/1.55.0
cd /home/borja.freire/TFM/Código/fast-mRMR-master/cpu-OpenMp/src/ScriptsPluton/BreastCancer/
cd ..
cd ..
cd NoParallel/
make clean
make
cd ../ScriptsPluton/BreastCancer/
for i in `seq 1 3`;
do
        ./../../NoParallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 50 >> ../../../Output-Pluton/BreastCancer/Optimized/breastMicroArray50FeaturesTotal
        ./../../NoParallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 100 >> ../../../Output-Pluton/BreastCancer/Optimized/breastMicroArray100FeaturesTotal
        ./../../NoParallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 200 >> ../../../Output-Pluton/BreastCancer/Optimized/breastMicroArray200FeaturesTotal
	./../../NoParallel/fast-mrmr -f /home2/borja.freire/Datasets/Mrmr/breast_preprocessed.mrmr -a 1000 >> ../../../Output-Pluton/BreastCancer/Optimized/breastMicroArray1000FeaturesTotal
done
