#!/bin/bash
#$ -l s_rt=60:00:00,mem_free=60G,cpu_type=sandy_bridge,excl=true
module load gcc/5.3.1 boost/gcc/openmpi-1.6.4/1.55.0
cd /home/borja.freire/TFM/Código/fast-mRMR-master/cpu-OpenMp/src/ScriptsPluton/BreastCancer/
cd ../../NoParallel/
make clean
make
cd ../ScriptsPluton/BreastCancer/
for i in `seq 1 3`;
do
        ./../../NoParallel/fast-mrmr -f $1 -a 50 >> $2
        ./../../NoParallel/fast-mrmr -f $1 -a 100 >> $2
        ./../../NoParallel/fast-mrmr -f $1 -a 200 >> $2
done
