#!/bin/bash
#$ -l s_rt=1:00:00,mem_free=0.5G,cpu_type=sandy_bridge,excl=true
module load gcc/5.3.1 boost/gcc/openmpi-1.7.2/1.55.0 openmpi/gcc/ib/1.7.2
cd /home/borja.freire/TFM/Código/fast-mRMR-master/cpu-OpenMp/src/ScriptsPluton/BreastCancer/
cd ..
cd ..
cd ParallelMPI/
make clean -f Makefile3
make -f Makefile3
cd ../ScriptsPluton/BreastCancer/
#$ -pe mpi_8p 64
        mpirun -np 64 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 50 >> $2
        mpirun -np 64 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 100 >> $2
        mpirun -np 64 --bind-to-socket -x OMP_NUM_THREADS=2 ./../../ParallelMPI/fast-mrmr -f $1 -a 200 >> $2
